var/docs/examples/survey/urls.py
# IMPORTS
# ---------------------------------------------------------------------------------------------------------------------#
from django.conf.urls import patterns, url
from django.views.generic.base import TemplateView
from survey.views import ProviderCreate, ProviderDelete, ProviderUpdate, ChallengeDetailUpdate, ChallengeDetailCreate


# URLS
# ---------------------------------------------------------------------------------------------------------------------#
urlpatterns = patterns(
    '',  # namespace

    url(r'^s/(?P<slug>\w{12,})/$', 'survey.views.login_user', name='login'),
    url(r'^welcome/$', 'survey.views.about', name='about'),
    url(r'^goodbye/$', TemplateView.as_view(template_name='survey/goodbye.html'), name='goodbye'),

    url(r'^$', 'survey.views.survey', name='survey'),

    url(r'^profile/$', 'survey.views.update_profile', name='update_profile'),
    url(r'^providers/$', 'survey.views.update_providers', name='update_providers'),
    url(r'^financial/$', 'survey.views.update_financial', name='update_financial'),
    url(r'^challenge/$', 'survey.views.update_challenge', name='update_challenge'),

    # url(r'^(?P<slug>\w{4,})/vas/(?P<vas_id>\d{1,3})', 'survey.views.update_provider', name='update_provider'),
    # url(r'^vas/$', 'survey.views.provider', name='provider'),

    # API Stuff
    # url(r'^provider/add/$', 'survey.views.create_provider', name='create_provider'),
    # url(r'^provider/update/(?P<pk>\d+)$', 'survey.views.update_provider', name='update_provider'),
    # url(r'^provider/delete/$', 'survey.views.delete_provider', name='delete_provider'),

    # url(r'^challenge_detail/$', 'survey.views.update_challenge_detail', name='update_challenge_detail'),
    # url(r'^playground/$', TemplateView.as_view(template_name='survey/index.html'), name='playground'),

    url(r'^service/add/$', 'survey.views.add_service', name='add_service'),
    url(r'^challenge/add/$', 'survey.views.add_challenge', name='add_challenge'),
    url(r'^challenge/reorder/$', 'survey.views.reorder_challenge', name='reorder_challenge'),
    url(r'^reliable/add/$', 'survey.views.add_reliable', name='add_reliable'),
    url(r'^period/add/$', 'survey.views.add_period', name='add_period'),

    url(r'^review/$', 'survey.views.update_section_status', name='update_section_status'),

    url(r'^provider/add/$', ProviderCreate.as_view(), name='provider_add'),
    url(r'^provider/(?P<pk>\d+)/$', ProviderUpdate.as_view(), name='provider_update'),
    url(r'^provider/(?P<pk>\d+)/delete/$', ProviderDelete.as_view(), name='provider_delete'),

    url(r'^challenge_detail/(?P<rank>\d+)/$', ChallengeDetailUpdate.as_view(), name='challenge_detail_update'),
    url(r'^challenge_detail/add/$', ChallengeDetailCreate.as_view(), name='challenge_detail_add'),

)

var/docs/examples/survey/models.py
# IMPORTS
# ---------------------------------------------------------------------------------------------------------------------#
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.core.validators import MinValueValidator, MaxValueValidator
from fact_book.models import Country, Currency
from logging import getLogger


# LOGGING
# ---------------------------------------------------------------------------------------------------------------------#
logger = getLogger('django')


# BASE MODELS
# ---------------------------------------------------------------------------------------------------------------------#
class NaturalManager(models.Manager):
    def get_by_natural_key(self, name):
        return self.get(name=name)


class NaturalModel(models.Model):
    name = models.CharField(max_length=150, unique=False)

    def natural_key(self):
        return (self.name, )

    objects = NaturalManager()

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


# MODELS
# ---------------------------------------------------------------------------------------------------------------------#
class Section(NaturalModel):
    started = models.BooleanField(default=False)
    approved = models.BooleanField(default=False)
    owner = models.SlugField(max_length=50, null=True, blank=True)


class Service(NaturalModel):
    private = models.BooleanField(default=False)
    owner = models.SlugField(max_length=50, null=True, blank=True)


class Reliable(NaturalModel):
    private = models.BooleanField(default=False)
    owner = models.SlugField(max_length=50, null=True, blank=True)

    class Meta:
        verbose_name = 'Attribute of Trusted VAS Vendors'
        verbose_name_plural = 'Attributes of Trusted VAS Vendors'


class Challenge(NaturalModel):
    private = models.BooleanField(default=False)
    owner = models.SlugField(max_length=50, null=True, blank=True)


class Period(NaturalModel):
    private = models.BooleanField(default=False)
    owner = models.SlugField(max_length=50, null=True, blank=True)

    class Meta:
        verbose_name = 'Acceptable ROI Period'
        verbose_name_plural = 'Acceptable ROI Periods'


class Survey(models.Model):
    user = models.OneToOneField(User)
    slug = models.SlugField(max_length=50, unique=True)

    is_section_0_reviewed = models.BooleanField(default=False)
    is_section_1_reviewed = models.BooleanField(default=False)
    is_section_2_reviewed = models.BooleanField(default=False)
    is_section_3_reviewed = models.BooleanField(default=False)

    section_0_empty = models.PositiveSmallIntegerField(default=0, null=True, blank=True)
    section_1_empty = models.PositiveSmallIntegerField(default=0, null=True, blank=True)
    section_2_empty = models.PositiveSmallIntegerField(default=0, null=True, blank=True)
    section_3_empty = models.PositiveSmallIntegerField(default=0, null=True, blank=True)

    name = models.CharField(max_length=150)

    # QUESTION 1
    # -----------------------------------------------------------------------------
    FEMALE = 'F'
    MALE = 'M'

    GENDER_CHOICES = (
        (FEMALE, 'Female'),
        (MALE, 'Male'),
    )
    gender = models.CharField(
        max_length=1,
        choices=GENDER_CHOICES,
        default=MALE,
        null=False,
        blank=False,
    )

    company_name = models.CharField(max_length=150)
    job_title = models.CharField(max_length=150, blank=True, null=True)
    country_of_operation = models.ForeignKey(Country, null=True, blank=True)
    # country_of_operation = ChoiceField(Country)
    email_address = models.EmailField()
    phone_number = models.CharField(max_length=20, help_text='e.g.: +27 28 123 4444', blank=True, null=True)

    # QUESTION 2
    # -----------------------------------------------------------------------------
    COUNTRY = 'C'
    REGION = 'R'

    COUNTRY_CHOICES = (
        (None, 'Please select an option...'),
        (COUNTRY, 'Country'),
        (REGION, 'Region'),
    )
    country_or_region = models.CharField(
        max_length=3,
        choices=COUNTRY_CHOICES,
        help_text='Please select appropriate value',
        null=True,
        blank=True,
    )

    countries = models.ManyToManyField(
        to=Country,
        related_name='responsible_countries',
        help_text='Start typing or select country from dropdown.',
        null=True,
        blank=True,
    )

    # QUESTION 3
    # -----------------------------------------------------------------------------
    VAS_CHOICES = (
        (None, 'Please select an option...'),
        ('L1', '0'),
        ('L6', '40+'),
    )

    vas_parties = models.CharField(
        max_length=3,
        choices=VAS_CHOICES,
        # default=COUNTRY,
        null=True,
        blank=True,
    )

    def get_absolute_url(self):
        # return 'http://%s/s/%s' % (Site.objects.get_current().domain, self.slug)
        return reverse('survey:login', kwargs={'slug': self.slug, })

    # QUESTION 5
    # -----------------------------------------------------------------------------
    PITCH_CHOICES = (
        (None, 'Please select an option...'),
        ('L1', 'Option'),
        ('L6', 'All'),
    )

    service_pitches = models.CharField(
        max_length=3,
        choices=PITCH_CHOICES,
        # default='L1',
        null=True,
        blank=True,
    )

    # QUESTION 6
    # -----------------------------------------------------------------------------
    Q6_CHOICES = (
        (None, 'Please select an option...'),
        ('L1', 'First'),
    )
    investments = models.CharField(
        max_length=2,
        choices=Q6_CHOICES,
        null=True,
        blank=True,
    )

    # QUESTION 7
    # -----------------------------------------------------------------------------
    # Q7. What were the total revenues generated by mobile VAS during the following month:
    currency = models.ForeignKey(
        to=Currency,
        null=True,
        blank=True,
        help_text="(omit currency and separators when filling in total revenue, e.g. 132000)"
    )
    # TODO: sort out question text

    revenue_mar_14 = models.BigIntegerField( null=True, blank=True)
    revenue_jun_14 = models.BigIntegerField( null=True, blank=True)
    revenue_sep_14 = models.BigIntegerField( null=True, blank=True)
    revenue_dec_14 = models.BigIntegerField( null=True, blank=True)

    # QUESTION 8
    # -----------------------------------------------------------------------------
    # Q8. Where does most of your revenue in VAS come from?
    revenue_streams = models.ManyToManyField(
        to=Service,
        null=True,
        blank=True,
    )

    revenue_stream_1 = models.ForeignKey(
        to=Service,
        related_name='revenue_stream_1',
        null=True,
        blank=True,
    )
    revenue_stream_2 = models.ForeignKey(
        to=Service,
        related_name='revenue_stream_2',
        null=True,
        blank=True,
    )
    revenue_stream_3 = models.ForeignKey(
        to=Service,
        related_name='revenue_stream_3',
        null=True,
        blank=True,
    )

    # QUESTION 9
    # -----------------------------------------------------------------------------
    # Q9. What percentage of your company revenues does VAS represent?
    # [Obligatory free text answer]
    vas_revenue_share = models.PositiveSmallIntegerField(
        max_length=15,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        null=True,
        blank=True,
        help_text='(please give the percentage as an integer between 0 and 100)'
    )

    # QUESTION 10
    # -----------------------------------------------------------------------------
    # Q10. How long is acceptable to wait for return on investment (ROI) on a new VAS?
    Q10_CHOICES = (
        ('L1', 'Invested less than last year'),
    )
    acceptable_roi_wait = models.ForeignKey(
        to=Period,
        null=True,
        blank=True,
        help_text='Use the textbox below to add another option to the drop-down.'
    )
    # 3 months
    # 6 months
    # 12 months
    # Other:

    # TODO: Dropdown with freetext

    # QUESTION 11
    # -----------------------------------------------------------------------------
    # Q11. What is the minimum percentage of return on investment at the end of the acceptable period identified in Q10?
    acceptable_roi_percentage = models.PositiveSmallIntegerField(
        max_length=25,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        null=True,
        blank=True,
        help_text='(please give the percentage as an integer between 0 and 100)'
    )

    # QUESTION 12
    # -----------------------------------------------------------------------------
    challenges = models.ManyToManyField(
        to=Challenge,
        help_text='(please tick all that apply)',
        null=True,
        blank=True,
    )

    # QUESTION 13/14
    # -----------------------------------------------------------------------------
    # biggest_challenge_1 = models.OneToOneField(
    # to=ChallengeDetail,
    #     related_name='challenge_1',
    #     null=True,
    #     blank=True,
    # )
    # biggest_challenge_2 = models.OneToOneField(
    #     to=ChallengeDetail,
    #     related_name='challenge_2',
    #     null=True,
    #     blank=True,
    # )
    # biggest_challenge_3 = models.OneToOneField(
    #     to=ChallengeDetail,
    #     related_name='challenge_3',
    #     null=True,
    #     blank=True,
    # )

    def __str__(self):
        return self.name


class ChallengeDetail(models.Model):
    respondent = models.ForeignKey(Survey, null=True, blank=True)
    challenge = models.ForeignKey(
        to=Challenge,
        null=True,
        blank=True,
        # help_text='(select from dropdown list)',
    )
    rank = models.PositiveSmallIntegerField(null=True, blank=True)

    # QUESTION 8

var/docs/examples/survey/templates/survey/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "favicon.ico" %}">

    <title>GSMA Survey</title>
    <link href="{% static "survey/css/style.min.css" %}" rel="stylesheet">

    {% block extra_style %}{% endblock %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 10]>
	<link rel="stylesheet" type="text/css" href="{% static "survey/css/ie.css" %}" />
    <script src="{% static "survey/js/lib/respond.min.js" %}"></script>
    <script src="{% static "survey/js/lib/html5shiv.min.js" %}"></script>
{#    <script src="{% static "survey/js/lib/jquery.placeholder-enhanced.js" %}"></script>#}
{#    <script src="{% static "survey/bower_components/better-dom/dist/better-dom-legacy.js" %}"></script>#}
{#    <script src="{% static "survey/bower_components/better-dom/dist/better-dom.js" %}"></script>#}
{#    <script src="{% static "survey/bower_components/better-placeholder-polyfill/dist/better-placeholder-polyfill.js" %}"></script>#}

    <![endif]-->

    {#<script src="{% static "bootstrap/js/ie10-viewport-bug-workaround.js" %}"></script>#}

    {% if False %}
        <script data-main="/static/survey/js/config"
                src="{% static "survey/bower_components/requirejs/require.js" %}"></script>
    {% else %}
        <script src="{% static "survey/js/main-built.js" %}"></script>
    {% endif %}

</head>

<body>


<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url "survey:about" %}">
                <img src="{% static "survey/img/logo.png" %}" alt="Logo">
            </a>
            <!--<a class="navbar-brand" href="#">GSMA Mobile for Development</a>-->
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url "survey:about" %}">HOME</a></li>
                <li class="active"><a href="{% url "survey:survey" %}">SURVEY</a></li>
            </ul>

        </div>

        <!--/.nav-collapse -->
    </div>
</nav>

<div id="loading">
    <img src="{% static "survey/img/wait.gif" %}"/>
    </br>
    <h2>Loading survey...</h2>

    <p>(if you still see this after 30 seconds please try refreshing the page)</p>
</div>

<!-- Begin page content -->
{% block content %}{% endblock %}


<!-- Footer -->
<footer class="footer">
    <div class="container">
        <p class="text-muted" style="float: left;">
			Footer
			<span id="whisper"><i>{{ request.session.survey_slug }}</i></span>
        </p>
    </div>
</footer>


{#    <!--[if lt IE 10]>#}
{#    <script src="{% static "survey/js/lib/jquery.placeholder-enhanced.js" %}"></script>#}
{#    <script src="{% static "survey/js/lib/ie-behavior-span.js" %}"></script>#}
{#    <![endif]-->#}

</body>
</html>

var/docs/examples/survey/templates/survey/challenge.html
{% if form %}
    {% load bootstrap3 %}
    {% bootstrap_messages %}

    <br>
    <form id="challenge_form" class="form" action="{% url 'survey:update_challenge' %}?tab=2" method="post" role="form">
        {% csrf_token %}

        <div id="other_challenge_container" class="well anti-well clearfix other">
            {% bootstrap_field form.challenges layout="" %}
            <div class="row">
                <div class="col-xs-4">
                    <div class="input-group">
                        <input id="other_challenge" type="text" class="form-control"
                               placeholder="Other (please specify...)"/>
                      <span class="input-group-btn">
                        <button id="other_challenge_button" class="btn btn-default" type="button">Add</button>
                      </span>
                    </div>
                    <!-- /input-group -->
                </div>
            </div>
        </div>

        <br/>

        <h3>Challenge Details</h3>
        <hr/>
        <br/>

        <div class="row">
            <div class="col-sm-12 col-md-8 col-lg-8">

            <table id="challenge-table" class="table table-hover">
                <thead>
                <tr>
                    <th></th>
                    <th>Rank</th>
                    <th>Description</th>
                    <th></th>
                </tr>
                </thead>
                {% for challenge in form.instance.challengedetail_set.all %}
                    <tr id="{{ forloop.counter }}">
                        <td class="drag-handle"></td>
                        <td>{{ forloop.counter }}</td>
                        <td>{% if challenge.challenge.name %}
                            {{ challenge.challenge.name }}
                        {% else %}
                            Not updated yet.
                        {% endif %}
                        </td>
                        <td style="text-align: right">
                            <a id="update_biggest_challenge_{{ forloop.counter }}" class="btn btn-sm btn-primary"
                               data-toggle="modal"
                               href="{% url "survey:challenge_detail_update" forloop.counter %}"
                               data-target="#challengeDetailModal" title="Update" data-tooltip>Update details</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        </div>

        {% buttons %}
            <br/>
            <button name="continue" class="btn btn-lg btn-primary" type="submit">Save & continue</button>
            <button name="close" class="btn btn-lg btn-primary" type="submit">Save & close</button>
        {% endbuttons %}
    </form>
{% endif %}

var/docs/examples/survey/templates/survey/challengedetail_form.html
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title" id="challengeDetailModalLabel">
        {% if object %}
            Update challenge details
        {% else %}
            Add challenge details
        {% endif %}
    </h4>
</div>

<div class="modal-body">
    {% load bootstrap3 %}
    {% bootstrap_messages %}

    {% if form %}
        {% if object %}
            <form method="POST" class="form" action="{% url 'survey:challenge_detail_update' object.rank %}" role="form"
                  id="challenge_detail_form">
        {% else %}
            <form method="POST" class="form" action="{% url 'survey:challenge_detail_add' %}" role="form"
                  id="challenge_detail_form">
        {% endif %}

    {% csrf_token %}


    {% bootstrap_field form.challenge %}

    <div id="other_attempted_services_container" class="well anti-well clearfix other">
        {% bootstrap_field form.attempted_services layout="" %}
        <div class="row">
            <div class="col-xs-4">
                <div class="input-group">
                    <input id="other_attempted_services" type="text" class="form-control"
                           placeholder="Other (please specify...)"/>
                      <span class="input-group-btn">
                        <button id="other_attempted_services_button" class="btn btn-default" type="button">Add</button>
                      </span>
                </div>
                <!-- /input-group -->
            </div>
        </div>
    </div>

    {% bootstrap_field form.pitch_source %}
    {% bootstrap_field form.year %}
    {% bootstrap_field form.challenge_details %}
    {% bootstrap_field form.solution_details %}


    <div class="modal-footer">
        {% buttons %}
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            {% if object %}
                <button type="submit" class="btn btn-primary">Update challenge details</button>
            {% else %}
                <button type="submit" class="btn btn-primary">Add challenge details</button>
            {% endif %}
        {% endbuttons %}
    </div>

    </form>
    {% endif %}

var/docs/examples/survey/templates/survey/financial.html
{% if form %}
    {% load bootstrap3 %}
    {% bootstrap_messages %}

    <form id="financial_form" class="form" action="{% url 'survey:update_financial' %}?tab=2" method="post" role="form">
        {% csrf_token %}

        {% bootstrap_field form.investments layout="" %}
        <div class="well clearfix anti-well">
            {% bootstrap_field form.currency layout="" %}
            <div class="row">{% bootstrap_field form.revenue_mar_14 layout="horizontal" %}</div>
            <div class="row">{% bootstrap_field form.revenue_jun_14 layout="horizontal" %}</div>
            <div class="row">{% bootstrap_field form.revenue_sep_14 layout="horizontal" %}</div>
            <div class="row">{% bootstrap_field form.revenue_dec_14 layout="horizontal" %}</div>
        </div>

        <p>Q3. Which three VAS generate the highest revenues for your company?

        <div class="row clearfix"
             style="margin-bottom: 10px;">{% bootstrap_field form.revenue_stream_1 layout="horizontal" %}</div>
        <div class="row clearfix"
             style="margin-bottom: 10px;">{% bootstrap_field form.revenue_stream_2 layout="horizontal" %}</div>
        <div class="row clearfix"
             style="margin-bottom: 10px;">{% bootstrap_field form.revenue_stream_3 layout="horizontal" %}</div>

        <span class="help-block">Use the textbox below to add another option to the dropdowns.</span>


        <div id="other_revenue_stream_container" class="well anti-well clearfix other">
            <div class="row">
                <div class="col-xs-4">
                    <div class="input-group input-group-sm">
                        <input id="other_revenue_stream" type="text" class="form-control"
                               placeholder="Other (please specify...)"/>
              <span class="input-group-btn">
                <button id="other_revenue_stream_button" class="btn btn-default" type="button">Add</button>
              </span>
                    </div>
                    <!-- /input-group -->
                </div>
            </div>
        </div>

        <br/>

        <div class="row">
            <div class="col-md-6">
                {% bootstrap_field form.vas_revenue_share addon_after='%' layout="" %}
            </div>
        </div>

        <div id="other_revenue_stream_container" class="well anti-well clearfix other">
            {% bootstrap_field form.acceptable_roi_wait layout="" %}

            <div class="row">
                <div class="col-xs-4">
                    <div class="input-group input-group-sm">
                        <input id="other_roi_period" type="text" class="form-control"
                               placeholder="Other (please specify...)"/>
              <span class="input-group-btn">
                <button id="other_roi_period_button" class="btn btn-default" type="button">Add</button>
              </span>
                    </div>
                    <!-- /input-group -->
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                {% bootstrap_field form.acceptable_roi_percentage addon_after='%' layout="" %}
            </div>
        </div>

        {% buttons %}
            <br/>
            <button name="continue" class="btn btn-lg btn-primary" type="submit">Save & continue</button>
            <button name="close" class="btn btn-lg btn-primary" type="submit">Save & close</button>
        {% endbuttons %}
    </form>

{% endif %}

var/docs/examples/survey/templates/survey/goodbye.html
{% extends "survey/base.html" %}

{% block content %}

    {% if request.user.is_staff %}
        <div class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
            <strong>Please note:</strong> You are viewing this survey as staff user "{{ request.user.username }}".
            You are able to make changes and save them on behalf of the respondent.
            Click <a href="/admin/survey/survey/">here</a> to go back to the list of surveys.
        </div>
    {% endif %}


    <div class="container">
        <div class="jumbotron">
            <h2>Thank you!</h2>
            <p>Your data has been saved and you can safely leave this page.
                If you want to return to this survey at a later stage, please use your
            unique link:</p>
            <a href="{% url 'survey:login' slug=request.session.survey_slug %}">http://m4dimpactsurvey.com{% url 'survey:login' slug=request.session.survey_slug %}</a>

        </div>
    </div>



{% endblock %}

var/docs/examples/survey/templates/survey/profile.html
{% if form %}
    {% load bootstrap3 %}
    {% bootstrap_messages %}

    <form id="profile_form" class="form-horizontal" action="{% url 'survey:update_profile' %}?tab=0" method="post" role="form">
        {% csrf_token %}

{#        {{ form.is_section_0_reviewed }}#}
{#        {{ form.is_section_1_reviewed }}#}
{#        {{ form.is_section_2_reviewed }}#}
{#        {{ form.is_section_3_reviewed }}#}


        {% bootstrap_field form.name layout="horizontal" %}
        {% bootstrap_field form.gender layout="horizontal" %}
        {% bootstrap_field form.company_name layout="horizontal" %}
        {% bootstrap_field form.job_title layout="horizontal" %}
        {% bootstrap_field form.country_of_operation layout="horizontal" %}
        {% bootstrap_field form.email_address layout="horizontal" %}
        {% bootstrap_field form.phone_number layout="horizontal" %}

{#        <h3>Role in organization:</h3><hr/>#}

        {% bootstrap_field form.country_or_region layout="" %}
        {% bootstrap_field form.countries layout="" %}
        {% bootstrap_field form.vas_parties layout="" %}
        {% bootstrap_field form.service_pitches layout="" %}

        {% buttons %}
            <br/>
            <button name="continue" class="btn btn-lg btn-primary" type="submit">Save & continue</button>
            <button name="close" class="btn btn-lg btn-primary" type="submit">Save & close</button>
        {% endbuttons %}

    </form>
{% endif %}
{% load static %}
{#     <script src="{% static "survey/js/lib/ie-behavior-span.js" %}"></script>#}

var/docs/examples/survey/templates/survey/progress.html
{% if form %}
    <form id="progress_form" method="post" role="form">
        {% csrf_token %}

        {{ form }}
{#        {{ form.is_section_1_reviewed }}#}
{#        {{ form.is_section_1_reviewed }}#}
{#        {{ form.is_section_2_reviewed }}#}
{#        {{ form.is_section_3_reviewed }}#}

    </form>
{% endif %}

var/docs/examples/survey/templates/survey/provider.html
{% if True %}
    {% load bootstrap3 %}
    {% bootstrap_messages %}

    <form id="provider_form" class="form" action="{% url 'survey:update_providers' %}?tab=1" method="post" role="form">
    {% csrf_token %}
    <input type="hidden" name="tab" value="1" />
    <input type="hidden" name="modal" value="success" />

		<p>Instructions...</p>

        <a id="add_provider_btn_top" class="btn btn-default" data-toggle="modal"
           href="{% url "survey:provider_add" %}"
           data-target="#providerAddModal" title="Add">Add object</a>

        <hr/>

        <div class="jumbotron">

            <!-- The feed -->
            <table class="table table-hover" id="provider">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Company Name</th>
                    <th>Contact Name</th>
                    <th>Contact Email</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for provider in providers %}
                    <tr id="provider-{{ provider.id }}">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ provider.vas_company_name }}</td>
                        <td>{{ provider.contact_name }}</td>
                        <td><a href="mailto:{{ provider.contact_email }}">{{ provider.contact_email }}</a>
                        </td>
                        <td>

                            <a class="btn btn-sm btn-primary" data-toggle="modal"
                               href="{% url "survey:provider_update" provider.id %}"
                               data-target="#providerAddModal" title="Edit" data-tooltip>Edit</a>

                            <a id='delete-provider-{{ provider.id }}' class="btn btn-sm btn-primary"
                               title="Delete"
                               data-tooltip>Delete</a>
                        </td>
                    </tr>
                {% empty %}

                    Please click "Add object" button to add vendors.

                {% endfor %}
                </tbody>
            </table>

<h4><span id="provider-count"></span> out of 10 providers added.</h4>

        </div>

        <a id="add_provider_btn_bottom" class="btn btn-default" data-toggle="modal"
           href="{% url "survey:provider_add" %}"
           data-target="#providerAddModal" title="Add">Add object</a>


        {% buttons %}
            <br/>
            <button name="continue" class="btn btn-lg btn-primary" type="submit">Save & continue</button>
            <button name="close" class="btn btn-lg btn-primary" type="submit">Save & close</button>
        {% endbuttons %}
    </form>
{% endif %}

var/docs/examples/survey/templates/survey/vasprovider_confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>